subject_id_col: person_id

person:
  death_time: # Relative Time, The time for death
    code: MEDS_DEATH
    time: col(date_of_death)
    time_format: "%Y-%m-%d %H:%M:%S"
  age: # Number, Age of the patient on the operation date
    code:
      - MEDS_BIRTH
    time: col(date_of_birth)
    time_format: "%Y-%m-%d %H:%M:%S"

observation:
  observation:
    code:
      - col(vocabulary_id)
      - col(concept_code)
    time: col(observation_datetime)
    time_format: "%Y-%m-%d %H:%M:%S"
    numeric_value: col(value_as_number)
    unit: col(unit_concept_id)
    text_value: col(value_as_string)
    visit_occurrence_id: col(visit_occurrence_id)

measurement:
  measurement:
    code:
      - col(vocabulary_id)
      - col(concept_code)
    time: col(measurement_datetime)
    time_format: "%Y-%m-%d %H:%M:%S"
    numeric_value: col(value_as_number)
    unit: col(unit_concept_id)
    visit_occurrence_id: col(visit_occurrence_id)

#        value_text: col(value_as_string)
visit_occurrence:
  visit:
    code:
      - visit
      - col(vocabulary_id)
      - col(visit_type_concept_id)
    time: col(visit_start_datetime)
    time_format: "%Y-%m-%d %H:%M:%S"
    visit_occurrence_id: col(visit_occurrence_id)
    end: col(visit_end_datetime)

  #        end_time: col(visit_end_datetime)
  visit_end:
    code:
      - visit_end
      - col(vocabulary_id)
      - col(concept_code)
    time: col(visit_end_datetime)
    time_format: "%Y-%m-%d %H:%M:%S"
    visit_occurrence_id: col(visit_occurrence_id)

observation_period:
  observation_period:
    code:
      - observation_period_start
      - col(period_type_concept_id)
    time: col(observation_period_start_date)
    time_format: "%Y-%m-%d %H:%M:%S"
    end: col(observation_period_end_date)
  observation_period_end:
    code:
      - observation_period_end
      - observation_period_start
      - col(period_type_concept_id)
    time: col(observation_period_end_date)
    time_format: "%Y-%m-%d %H:%M:%S"

drug_exposure:
  drug_exposure:
    code:
      - drug_exposure_start
      - col(vocabulary_id)
      - col(drug_concept_id)
    time: col(drug_exposure_start_datetime)
    numeric_value: col(quantity)
    time_format: "%Y-%m-%d %H:%M:%S"
    visit_occurrence_id: col(visit_occurrence_id)
    end: col(drug_exposure_end_datetime)

  drug_exposure_end:
    code:
      - drug_exposure_end
      - col(vocabulary_id)
      - col(drug_concept_id)
    time: col(drug_exposure_end_datetime)
    time_format: "%Y-%m-%d %H:%M:%S"
    visit_occurrence_id: col(visit_occurrence_id)

specimen:
  specimen:
    code:
      - specimen
      - col(specimen_concept_id)
    time: col(specimen_datetime)
    time_format: "%Y-%m-%d %H:%M:%S"
    numeric_value: col(quantity)
    unit: col(unit_concept_id)

device_exposure:
  device_exposure:
    code:
      - device_exposure_start
      - col(vocabulary_id)
      - col(device_concept_id)
    time: col(device_exposure_start_datetime)
    time_format: "%Y-%m-%d %H:%M:%S"
    numeric_value: col(quantity)
    visit_occurrence_id: col(visit_occurrence_id)
    end: col(device_exposure_end_datetime)

  device_exposure_end:
    code:
      - device_exposure_end
      - col(vocabulary_id)
      - col(device_concept_id)
    time: col(device_exposure_end_datetime)
    numeric_value: col(quantity)
    time_format: "%Y-%m-%d %H:%M:%S"
    visit_occurrence_id: col(visit_occurrence_id)

dose_era:
  dose_era:
    code:
      - dose_era_start
      - col(drug_concept_id)
    time: col(dose_era_start_date)
    time_format: "%Y-%m-%d %H:%M:%S"
    end: col(dose_era_end_date)
    numeric_value: col(dose_value)
    unit: col(unit_concept_id)
  dose_era_end:
    code:
      - dose_era_end
      - col(drug_concept_id)
    time: col(dose_era_end_date)
    time_format: "%Y-%m-%d %H:%M:%S"
    numeric_value: col(dose_value)
    unit: col(unit_concept_id)

condition_occurrence:
  condition_occurrence:
    code:
      - condition_occurrence
      - col(vocabulary_id)
      - col(condition_concept_id)
    time: col(condition_start_datetime)
    time_format: "%Y-%m-%d %H:%M:%S"
    visit_occurrence_id: col(visit_occurrence_id)
    end: col(condition_end_datetime)
  condition_end:
    code:
      - condition_end
      - col(vocabulary_id)
      - col(condition_concept_id)
    time: col(condition_end_datetime)
    time_format: "%Y-%m-%d %H:%M:%S"
    visit_occurrence_id: col(visit_occurrence_id)

drug_era:
  drug_era:
    code:
      - drug_era_start
      - col(vocabulary_id)
      - col(drug_concept_id)
    time: col(drug_era_start_date)
    time_format: "%Y-%m-%d %H:%M:%S"
    numeric_value: col(drug_exposure_count)
    end: col(drug_era_end_date)
  drug_era_end:
    code:
      - drug_era_end
      - col(vocabulary_id)
      - col(drug_concept_id)
    time: col(drug_era_end_date)
    time_format: "%Y-%m-%d %H:%M:%S"
    numeric_value: col(drug_exposure_count)

procedure_occurrence:
  procedure_occurrence:
    code:
      - procedure_occurrence
      - col(vocabulary_id)
      - col(procedure_concept_id)
    time: col(procedure_datetime)
    time_format: "%Y-%m-%d %H:%M:%S"
    numeric_value: col(quantity)
    visit_occurrence_id: col(visit_occurrence_id)

# only available in OMOP 5.4
#    procedure_end:
#        code:
#          - procedure_occurrence_end
#          - col(vocabulary_id)
#          - col(procedure_concept_id)
#        time: col(procedure_end_datetime)
#        time_format: "%Y-%m-%d %H:%M:%S"

condition_era:
  condition_era:
    code:
      - condition_era_start_date
      - col(vocabulary_id)
      - col(condition_concept_id)
    time: col(condition_era_start_date)
    time_format: "%Y-%m-%d %H:%M:%S"
    numeric_value: col(condition_occurrence_count)
    end: col(condition_era_end_date)
  condition_era_end:
    code:
      - condition_era_end_date
      - col(vocabulary_id)
      - col(condition_concept_id)
    time: col(condition_era_end_date)
    time_format: "%Y-%m-%d %H:%M:%S"
    numeric_value: col(condition_occurrence_count)
