subject_id_col: person_id

person_birth_death:
  death_time:
    code: MEDS_DEATH
    time: $date_of_death
    table_name: $table_name
  age:
    code: MEDS_BIRTH
    time: $date_of_birth
    table_name: $table_name
  gender:
    code: 'f"GENDER//{$gender}"'
    time: null
    table_name: $table_name

person:
  race:
    code: 'f"RACE//{$race_concept_id}"'
    time: null
    table_name: $table_name
  ethnicity:
    code: 'f"ETHNICITY//{$ethnicity_concept_id}"'
    time: null
    table_name: $table_name

observation:
  observation:
    code: 'f"{$preferred_vocabulary_name}//{$preferred_concept_name}"'
    time: $observation_datetime
    numeric_value: $value_as_number
    unit: $unit_concept_id
    text_value: $value_as_string
    visit_occurrence_id: $visit_occurrence_id
    table_name: $table_name

measurement:
  measurement:
    code: 'f"{$preferred_vocabulary_name}//{$preferred_concept_name}"'
    time: $measurement_datetime
    numeric_value: $value_as_number
    unit: $unit_concept_id
    visit_occurrence_id: $visit_occurrence_id
    table_name: $table_name

visit_occurrence:
  visit:
    code: 'f"{$preferred_vocabulary_name}//{$preferred_concept_name}//start"'
    time: $visit_start_datetime
    visit_occurrence_id: $visit_occurrence_id
    text_value: $care_site_name
    table_name: $table_name
  visit_end:
    code: 'f"{$preferred_vocabulary_name}//{$preferred_concept_name}//end"'
    time: $visit_end_datetime
    visit_occurrence_id: $visit_occurrence_id
    table_name: $table_name

observation_period:
  observation_period:
    code: 'f"{$preferred_vocabulary_name}//{$preferred_concept_name}//start"'
    time: $observation_period_start_date
    table_name: $table_name
  observation_period_end:
    code: 'f"{$preferred_vocabulary_name}//{$preferred_concept_name}//end"'
    time: $observation_period_end_date
    table_name: $table_name

drug_exposure:
  drug_exposure:
    code: 'f"{$preferred_vocabulary_name}//{$drug_concept_id}//start"'
    time: $drug_exposure_start_datetime
    numeric_value: $quantity
    visit_occurrence_id: $visit_occurrence_id
    table_name: $table_name
  drug_exposure_end:
    code: 'f"{$preferred_vocabulary_name}//{$drug_concept_id}//end"'
    time: $drug_exposure_end_datetime
    visit_occurrence_id: $visit_occurrence_id
    table_name: $table_name

specimen:
  specimen:
    code: 'f"{$preferred_vocabulary_name}//{$specimen_concept_id}"'
    time: $specimen_datetime
    numeric_value: $quantity
    unit: $unit_concept_id
    table_name: $table_name

device_exposure:
  device_exposure:
    code: 'f"{$preferred_vocabulary_name}//{$device_concept_id}//start"'
    time: $device_exposure_start_datetime
    numeric_value: $quantity
    visit_occurrence_id: $visit_occurrence_id
    table_name: $table_name
  device_exposure_end:
    code: 'f"{$preferred_vocabulary_name}//{$preferred_concept_name}//end"'
    time: $device_exposure_end_datetime
    numeric_value: $quantity
    visit_occurrence_id: $visit_occurrence_id
    table_name: $table_name

dose_era:
  dose_era:
    code: 'f"{$preferred_vocabulary_name}//{$preferred_concept_name}//start"'
    time: $dose_era_start_date
    numeric_value: $dose_value
    unit: $unit_concept_id
    table_name: $table_name
  dose_era_end:
    code: 'f"{$preferred_vocabulary_name}//{$preferred_concept_name}//end"'
    time: $dose_era_end_date
    numeric_value: $dose_value
    unit: $unit_concept_id
    table_name: $table_name

condition_occurrence:
  condition_occurrence:
    code: 'f"{$preferred_vocabulary_name}//{$preferred_concept_name}//start"'
    time: $condition_start_datetime
    visit_occurrence_id: $visit_occurrence_id
    table_name: $table_name
  condition_end:
    code: 'f"{$preferred_vocabulary_name}//{$preferred_concept_name}//end"'
    time: $condition_end_datetime
    visit_occurrence_id: $visit_occurrence_id
    table_name: $table_name

drug_era:
  drug_era:
    code: 'f"{$preferred_vocabulary_name}//{$preferred_concept_name}//start"'
    time: $drug_era_start_date
    numeric_value: $drug_exposure_count
    table_name: $table_name
  drug_era_end:
    code: 'f"{$preferred_vocabulary_name}//{$preferred_concept_name}//end"'
    time: $drug_era_end_date
    numeric_value: $drug_exposure_count
    table_name: $table_name

procedure_occurrence:
  procedure_occurrence:
    code: 'f"{$preferred_vocabulary_name}//{$preferred_concept_name}"'
    time: $procedure_datetime
    numeric_value: $quantity
    visit_occurrence_id: $visit_occurrence_id
    table_name: $table_name

condition_era:
  condition_era:
    code: 'f"{$preferred_vocabulary_name}//{$preferred_concept_name}//start"'
    time: $condition_era_start_date
    numeric_value: $condition_occurrence_count
    table_name: $table_name
  condition_era_end:
    code: 'f"{$preferred_vocabulary_name}//{$preferred_concept_name}//end"'
    time: $condition_era_end_date
    numeric_value: $condition_occurrence_count
    table_name: $table_name

note:
  note:
    code: 'f"{$preferred_vocabulary_name}//{$preferred_concept_name}"'
    time: $preferred_time
    text_value: $note_title
    visit_occurrence_id: $visit_occurrence_id
    table_name: $table_name
    link_id: $note_id
