subject_id_col: person_id

person:
  death_time: # Relative Time, The time for death
    code: MEDS_DEATH
    time: col(date_of_death)
    time_format: "%Y-%m-%d %H:%M:%S"
  age: # Number, Age of the patient on the operation date
    code:
      - MEDS_BIRTH
    time: col(date_of_birth)
    time_format: "%Y-%m-%d %H:%M:%S"

observation:
  observation:
    code:
      - col(vocabulary_id)
      - col(concept_code)
    time: col(observation_datetime)
    time_format: "%Y-%m-%d %H:%M:%S"
    value: col(value_as_number)
    value_unit: col(unit_concept_id)
    value_text: col(value_as_string)

measurement:
  measurement:
    code:
      - col(vocabulary_id)
      - col(concept_code)
    time: col(measurement_datetime)
    time_format: "%Y-%m-%d %H:%M:%S"
    value: col(value_as_number)
    value_unit: col(unit_concept_id)
#        value_text: col(value_as_string)
visit_occurrence:
  visit:
    code:
      - visit
      - col(vocabulary_id)
      - col(visit_type_concept_id)
    time: col(visit_start_datetime)
    time_format: "%Y-%m-%d %H:%M:%S"
  #        end_time: col(visit_end_datetime)
  visit_end:
    code:
      - visit_end
      - col(vocabulary_id)
      - col(concept_code)
    time: col(visit_end_datetime)
    time_format: "%Y-%m-%d %H:%M:%S"

observation_period:
    observation_period:
        code:
          - observation_period_start
          - col(period_type_concept_id)
        time: col(observation_period_start_date)
        time_format: "%Y-%m-%d %H:%M:%S"
    observation_period_end:
        code:
          - observation_period_end
          - observation_period_start
          - col(period_type_concept_id)
        time: col(observation_period_end_date)
        time_format: "%Y-%m-%d %H:%M:%S"

drug_exposure:
    drug_exposure:
        code:
          - drug_exposure_start
          - col(vocabulary_id)
          - col(drug_concept_id)
        time: col(drug_exposure_start_datetime)
        time_format: "%Y-%m-%d %H:%M:%S"
    drug_exposure_end:
        code:
          - drug_exposure_end
          - col(vocabulary_id)
          - col(drug_concept_id)
        time: col(drug_exposure_end_datetime)
        time_format: "%Y-%m-%d %H:%M:%S"

specimen:
    specimen:
        code:
          - specimen
          - col(specimen_concept_id)
        time: col(specimen_datetime)
        time_format: "%Y-%m-%d %H:%M:%S"

device_exposure:
    device_exposure:
        code:
          - device_exposure_start
          - col(vocabulary_id)
          - col(device_concept_id)
        time: col(device_exposure_start_datetime)
        time_format: "%Y-%m-%d %H:%M:%S"
    device_exposure_end:
        code:
          - device_exposure_end
          - col(vocabulary_id)
          - col(device_concept_id)
        time: col(device_exposure_end_datetime)
        time_format: "%Y-%m-%d %H:%M:%S"

dose_era:
    dose_era:
        code:
          - dose_era_start
          - col(drug_concept_id)
        time: col(dose_era_start_date)
        time_format: "%Y-%m-%d %H:%M:%S"
    dose_era_end:
        code:
          - dose_era_end
          - col(drug_concept_id)
        time: col(dose_era_end_date)
        time_format: "%Y-%m-%d %H:%M:%S"

condition_occurrence:
    condition_occurrence:
        code:
          - condition_occurrence
          - col(vocabulary_id)
          - col(condition_concept_id)
        time: col(condition_start_datetime)
        time_format: "%Y-%m-%d %H:%M:%S"
    condition_end:
        code:
          - condition_end
          - col(vocabulary_id)
          - col(condition_concept_id)
        time: col(condition_end_datetime)
        time_format: "%Y-%m-%d %H:%M:%S"

drug_era:
    drug_era:
        code:
          - drug_era_start
          - col(vocabulary_id)
          - col(drug_concept_id)
        time: col(drug_era_start_date)
        time_format: "%Y-%m-%d %H:%M:%S"
    drug_era_end:
        code:
          - drug_era_end
          - col(vocabulary_id)
          - col(drug_concept_id)
        time: col(drug_era_end_date)
        time_format: "%Y-%m-%d %H:%M:%S"

procedure_occurrence:
    procedure_occurrence:
        code:
          - procedure_occurrence
          - col(vocabulary_id)
          - col(procedure_concept_id)
        time: col(procedure_datetime)
        time_format: "%Y-%m-%d %H:%M:%S"
# only available in OMOP 5.4
#    procedure_end:
#        code:
#          - procedure_occurrence_end
#          - col(vocabulary_id)
#          - col(procedure_concept_id)
#        time: col(procedure_end_datetime)
#        time_format: "%Y-%m-%d %H:%M:%S"

condition_era:
    condition_era:
        code:
          - condition_era_start_date
          - col(vocabulary_id)
          - col(condition_concept_id)
        time: col(condition_era_start_date)
        time_format: "%Y-%m-%d %H:%M:%S"
    condition_era_end:
        code:
          - condition_era_end_date
          - col(vocabulary_id)
          - col(condition_concept_id)
        time: col(condition_era_end_date)
        time_format: "%Y-%m-%d %H:%M:%S"

#hosp/admissions:
#  ed_registration:
#    code: ED_REGISTRATION
#    time: col(edregtime)
#    time_format: "%Y-%m-%d %H:%M:%S"
#  ed_out:
#    code: ED_OUT
#    time: col(edouttime)
#    time_format: "%Y-%m-%d %H:%M:%S"
#  admission:
#    code:
#      - HOSPITAL_ADMISSION
#      - col(admission_type)
#      - col(admission_location)
#    time: col(admittime)
#    time_format: "%Y-%m-%d %H:%M:%S"
#    insurance: insurance
#    language: language
#    marital_status: marital_status
#    race: race
#    hadm_id: hadm_id
#  discharge:
#    code:
#      - HOSPITAL_DISCHARGE
#      - col(discharge_location)
#    time: col(dischtime)
#    time_format: "%Y-%m-%d %H:%M:%S"
#    hadm_id: hadm_id
#  # We omit the death event here as it is joined to the data in the subjects table in the pre-MEDS step.
#
#hosp/diagnoses_icd:
#  diagnosis:
#    code:
#      - DIAGNOSIS
#      - ICD
#      - col(icd_version)
#      - col(icd_code)
#    hadm_id: hadm_id
#    time: col(hadm_discharge_time)
#    time_format: "%Y-%m-%d %H:%M:%S"
#    _metadata:
#      hosp/d_icd_diagnoses:
#        description: "long_title"
#        parent_codes: "ICD{icd_version}CM/{norm_icd_code}" # Single strings are templates of columns.
#
#hosp/drgcodes:
#  drg:
#    code:
#      - DRG
#      - col(drg_type)
#      - col(drg_code)
#      - col(description)
#    hadm_id: hadm_id
#    time: col(hadm_discharge_time)
#    time_format: "%Y-%m-%d %H:%M:%S"
#    drg_severity: drg_severity
#    drg_mortality: drg_mortality
#
#hosp/emar:
#  medication:
#    code:
#      - MEDICATION
#      - col(medication)
#      - col(event_txt)
#    time: col(charttime)
#    time_format: "%Y-%m-%d %H:%M:%S"
#    hadm_id: hadm_id
#    emar_id: emar_id
#    emar_seq: emar_seq
#
#hosp/hcpcsevents:
#  hcpcs:
#    code:
#      - HCPCS
#      - col(short_description)
#    hadm_id: hadm_id
#    time: col(chartdate)
#    time_format: "%Y-%m-%d"
#    _metadata:
#      # These are not all CPT codes, unfortunately
#      hosp/d_hcpcs:
#        description: "long_description"
#        possibly_cpt_code: "code"
#
#hosp/labevents:
#  lab:
#    code:
#      - LAB
#      - col(itemid)
#      - col(valueuom)
#    hadm_id: hadm_id
#    time: col(charttime)
#    time_format: "%Y-%m-%d %H:%M:%S"
#    numeric_value: valuenum
#    text_value: value
#    priority: priority
#    _metadata:
#      d_labitems_to_loinc:
#        description: ["omop_concept_name", "label"] # List of strings are columns to be collated
#        itemid: "itemid (omop_source_code)"
#        parent_codes: "{omop_vocabulary_id}/{omop_concept_code}"
#        valueuom: "valueuom"
#
#hosp/omr:
#  omr:
#    code: col(result_name)
#    text_value: col(result_value)
#    time: col(chartdate)
#    time_format: "%Y-%m-%d"
#
#hosp/patients:
#  gender:
#    code:
#      - GENDER
#      - col(gender)
#    time: null
#  dob:
#    code: MEDS_BIRTH # This is the MEDS official code for birth.
#    time: col(year_of_birth)
#    time_format: "%Y"
#  death:
#    code: MEDS_DEATH # This is the MEDS official code for death.
#    time: col(dod)
#    time_format:
#      - "%Y-%m-%d %H:%M:%S"
#      - "%Y-%m-%d"
#
#hosp/pharmacy:
#  medication_start:
#    code:
#      - MEDICATION
#      - START
#      - col(medication)
#    time: col(starttime)
#    route: route
#    frequency: frequency
#    doses_per_24_hrs: doses_per_24_hrs
#    poe_id: poe_id
#    time_format:
#      - "%Y-%m-%d %H:%M:%S"
#      - "%Y-%m-%d"
#  medication_stop:
#    code:
#      - MEDICATION
#      - STOP
#      - col(medication)
#    time: col(stoptime)
#    poe_id: poe_id
#    time_format:
#      - "%Y-%m-%d %H:%M:%S"
#      - "%Y-%m-%d"
#
#hosp/procedures_icd:
#  procedure:
#    code:
#      - PROCEDURE
#      - ICD
#      - col(icd_version)
#      - col(icd_code)
#    hadm_id: hadm_id
#    time: col(chartdate)
#    time_format: "%Y-%m-%d"
#    _metadata:
#      hosp/d_icd_procedures:
#        description: "long_title"
#        parent_codes: # List of objects are string labels mapping to filters to be evaluated.
#          - "ICD{icd_version}Proc/{norm_icd_code}": { icd_version: "9" }
#          - "ICD{icd_version}PCS/{norm_icd_code}": { icd_version: "10" }
#
#hosp/transfers:
#  transfer:
#    code:
#      - TRANSFER_TO
#      - col(eventtype)
#      - col(careunit)
#    time: col(intime)
#    time_format: "%Y-%m-%d %H:%M:%S"
#    hadm_id: hadm_id
#
#icu/icustays:
#  icu_admission:
#    code:
#      - ICU_ADMISSION
#      - col(first_careunit)
#    time: col(intime)
#    time_format: "%Y-%m-%d %H:%M:%S"
#    hadm_id: hadm_id
#    icustay_id: stay_id
#  icu_discharge:
#    code:
#      - ICU_DISCHARGE
#      - col(last_careunit)
#    time: col(outtime)
#    time_format: "%Y-%m-%d %H:%M:%S"
#    hadm_id: hadm_id
#    icustay_id: stay_id
#
#icu/chartevents:
#  event:
#    code:
#      - LAB
#      - col(itemid)
#      - col(valueuom)
#    time: col(charttime)
#    time_format: "%Y-%m-%d %H:%M:%S"
#    numeric_value: valuenum
#    text_value: value
#    hadm_id: hadm_id
#    icustay_id: stay_id
#    _metadata:
#      # TODO: make this work even with missing valueuom
#      #meas_chartevents_main:
#      #  description: ["omop_concept_name", "label"] # List of strings are columns to be collated
#      #  itemid: "itemid (omop_source_code)"
#      #  parent_codes: "{omop_vocabulary_id}/{omop_concept_code}"
#      # TODO: I don't know if this is necessary...
#      d_labitems_to_loinc:
#        description: ["omop_concept_name", "label"] # List of strings are columns to be collated
#        itemid: "itemid (omop_source_code)"
#        parent_codes: "{omop_vocabulary_id}/{omop_concept_code}"
#        valueuom: "valueuom"
#
#icu/procedureevents:
#  start:
#    code:
#      - PROCEDURE
#      - START
#      - col(itemid)
#    time: col(starttime)
#    time_format: "%Y-%m-%d %H:%M:%S"
#    hadm_id: hadm_id
#    icustay_id: stay_id
#    _metadata:
#      proc_datetimeevents:
#        description: ["omop_concept_name", "label"] # List of strings are columns to be collated
#        itemid: "itemid (omop_source_code)"
#        parent_codes: "{omop_vocabulary_id}/{omop_concept_code}"
#      proc_itemid:
#        description: ["omop_concept_name", "label"] # List of strings are columns to be collated
#        itemid: "itemid (omop_source_code)"
#        parent_codes: "{omop_vocabulary_id}/{omop_concept_code}"
#  end:
#    code:
#      - PROCEDURE
#      - END
#      - col(itemid)
#    time: col(endtime)
#    time_format: "%Y-%m-%d %H:%M:%S"
#    hadm_id: hadm_id
#    icustay_id: stay_id
#    _metadata:
#      proc_datetimeevents:
#        description: ["omop_concept_name", "label"] # List of strings are columns to be collated
#        itemid: "itemid (omop_source_code)"
#        parent_codes: "{omop_vocabulary_id}/{omop_concept_code}"
#      proc_itemid:
#        description: ["omop_concept_name", "label"] # List of strings are columns to be collated
#        itemid: "itemid (omop_source_code)"
#        parent_codes: "{omop_vocabulary_id}/{omop_concept_code}"
#
#icu/inputevents:
#  input_start:
#    code:
#      - INFUSION_START
#      - col(itemid)
#    time: col(starttime)
#    time_format: "%Y-%m-%d %H:%M:%S"
#    hadm_id: hadm_id
#    icustay_id: stay_id
#    order_id: orderid
#    link_order_id: linkorderid
#    numeric_value: rate
#    unit: rateuom
#    ordercategorydescription: ordercategorydescription
#    _metadata:
#      inputevents_to_rxnorm:
#        description: ["omop_concept_name", "label"] # List of strings are columns to be collated
#        itemid: "itemid (omop_source_code)"
#        parent_codes: "{omop_vocabulary_id}/{omop_concept_code}"
#  input_end:
#    code:
#      - INFUSION_END
#      - col(itemid)
#    time: col(endtime)
#    time_format: "%Y-%m-%d %H:%M:%S"
#    hadm_id: hadm_id
#    icustay_id: stay_id
#    order_id: orderid
#    link_order_id: linkorderid
#    numeric_value: amount
#    ordercategorydescription: ordercategorydescription
#    statusdescription: statusdescription
#    unit: amountuom
#    _metadata:
#      inputevents_to_rxnorm:
#        description: ["omop_concept_name", "label"] # List of strings are columns to be collated
#        itemid: "itemid (omop_source_code)"
#        parent_codes: "{omop_vocabulary_id}/{omop_concept_code}"
#  subject_weight:
#    code:
#      - SUBJECT_WEIGHT_AT_INFUSION
#      - KG
#    time: col(starttime)
#    time_format: "%Y-%m-%d %H:%M:%S"
#    numeric_value: patientweight
#
#icu/outputevents:
#  output:
#    code:
#      - SUBJECT_FLUID_OUTPUT
#      - col(itemid)
#      - col(valueuom)
#    time: col(charttime)
#    time_format: "%Y-%m-%d %H:%M:%S"
#    hadm_id: hadm_id
#    icustay_id: stay_id
#    numeric_value: value
#    _metadata:
#      outputevents_to_loinc:
#        description: ["omop_concept_name", "label"] # List of strings are columns to be collated
#        itemid: "itemid (omop_source_code)"
#        valueuom: "unitname"
#        parent_codes: "{omop_vocabulary_id}/{omop_concept_code}"
