5.3:
  tables:
    - person
    - observation_period
    - visit_occurrence
    - visit_detail
    - condition_occurrence
    - drug_exposure
    - procedure_occurrence
    - device_exposure
    - measurement
    - observation
    - death
    - note
    - note_nlp
    - specimen
    - fact_relationship
    - location
    - care_site
    - provider
    - payer_plan_period
    - cost
    - drug_era
    - dose_era
    - condition_era
    - metadata
    - cdm_source
    - concept
    - vocabulary
    - domain
    - concept_class
    - concept_relationship
    - relationship
    - concept_synonym
    - concept_ancestor
    - source_to_concept_map
    - drug_strength
    - cohort_definition
    - attribute_definition

5.4:
  tables:
    - person
    - observation_period
    - visit_occurrence
    - visit_detail
    - condition_occurrence
    - drug_exposure
    - procedure_occurrence
    - device_exposure
    - measurement
    - observation
    - death
    - note
    - note_nlp
    - specimen
    - fact_relationship
    - location
    - care_site
    - provider
    - payer_plan_period
    - cost
    - drug_era
    - dose_era
    - condition_era
    - episode
    - episode_event
    - metadata
    - cdm_source
    - concept
    - vocabulary
    - domain
    - concept_class
    - concept_relationship
    - relationship
    - concept_synonym
    - concept_ancestor
    - source_to_concept_map
    - drug_strength
    - cohort
    - cohort_definition
