# OUTPUT DATA cols should never contain case_id or patient_id
subject_id: "person_id"
admission_id: "visit_occurrence_id"
raw_data_extensions: [ "*.parquet", "*.csv", "*.csv.gz" ]

person:
  # No offset in OMOP
  offset_col: [ ]
  # No pseudotime in OMOP
  pseudotime_col: [ ]
  # Column that contains ID's to concepts
  reference_col: [ ]
  output_data_cols: [
    "year_of_birth",
    "month_of_birth",
    "day_of_birth",
    "birth_datetime",
    "race_concept_id",
    "ethnicity_concept_id",
    "location_id",
    "provider_id",
    "care_site_id",
    "person_source_value",
    "gender_source_value",
    "gender_source_concept_id",
    "race_source_value",
    "race_source_concept_id",
    "ethnicity_source_value",
    "ethnicity_source_concept_id"
  ]
observation:
  offset_col: [ ]
  # No pseudotime in OMOP
  pseudotime_col: [ ]
  reference_col: [ "observation_source_concept_id" ]
  output_data_cols: [
    "observation_id",
    "observation_concept_id",
    "observation_date",
    "observation_datetime",
    #    "observation_type_concept_id",
    "value_as_number",
    "value_as_string",
    "value_as_concept_id",
    "qualifier_concept_id",
    "unit_concept_id",
    "provider_id",
    #    "visit_occurrence_id",
    #    "visit_detail_id",
    "observation_source_value",
    #    "observation_source_concept_id",
    "unit_source_value",
    "qualifier_source_value",
    "vocabulary_id" ]

measurement:
  offset_col: [ ]
  reference_col: [ "measurement_source_concept_id" ]
  output_data_cols: [
    "measurement_id",
    "measurement_concept_id",
    "measurement_date",
    "measurement_datetime",
    "measurement_time",
    "measurement_type_concept_id",
    "operator_concept_id",
    "value_as_number",
    "value_as_concept_id",
    "unit_concept_id",
    "range_low",
    "range_high",
    "provider_id",
    "visit_occurrence_id",
    "visit_detail_id",
    "measurement_source_value",
    "measurement_source_concept_id",
    "unit_source_value",
    "value_source_value",
    "vocabulary_id" ]

visit_occurrence:
  offset_col: [ ]
  pseudotime_col: [ ]
  reference_col: [ "visit_type_source_concept_id" ]
  output_data_cols: [
    "visit_occurrence_id",
    "visit_concept_id",
    "visit_start_date",
    "visit_start_datetime",
    "visit_end_date",
    "visit_end_datetime",
    "visit_type_concept_id",
    "provider_id",
    "care_site_id",
    "visit_source_value",
    "visit_source_concept_id",
    "admitting_source_concept_id",
    "admitting_source_value",
    "discharge_to_concept_id",
    "discharge_to_source_value",
    "preceding_visit_occurrence_id",
    "vocabulary_id" ]


#TODO: how to handle source
#concept:
#  offset_col: [ ]
#  pseudotime_col: [ ]
#  reference_col: [ "concept_id" ]
#  output_data_cols: [
#    "concept_name",
#    "domain_id",
#    "vocabulary_id",
#    "concept_class_id",
#    "standard_concept",
#    "concept_code",
#    "valid_start_DATE",
#    "valid_end_DATE",
#    "invalid_reason", ]

#death:
#  reference_col: [ "death_type_concept_id", "cause_concept_id", "cause_source_concept_id", "cause_source_value" ]
#  output_data_cols: [ "death_date", "death_datetime", ]
